import * as THREE from 'three';

/**
 * The company we keep. Real objects, real numbers; the one-liners are ours.
 * `dir` is the direction on the sky (normalised below), `view` is how far the
 * camera parks from the object when you jump to it, `size` the sprite scale.
 */
export const STAR_SHELL = 240;

const raw = [
  {
    id: 'sirius',
    name: 'Sirius',
    designation: 'α Canis Majoris · HD 48915',
    kind: 'star',
    type: 'A1V main-sequence star',
    spectral: 'A1V · 9,940 K',
    distance: '8.6 light-years',
    ly: 8.6,
    color: '#dfe9ff',
    size: 9,
    view: 12,
    dir: [0.62, 0.34, -0.71],
    lore: 'the brightest star in earth’s night. a white dwarf circles it, unseen.',
  },
  {
    id: 'proxima',
    name: 'Proxima Centauri',
    designation: 'V645 Centauri · GJ 551',
    kind: 'star',
    type: 'M5.5Ve red dwarf, flare star',
    spectral: 'M5.5Ve · 3,040 K',
    distance: '4.24 light-years',
    ly: 4.24,
    color: '#ff8a7a',
    size: 4.5,
    view: 7,
    dir: [-0.74, -0.22, -0.63],
    lore: 'the nearest star to the sun. a planet in its habitable zone keeps its own weather.',
  },
  {
    id: 'vega',
    name: 'Vega',
    designation: 'α Lyrae · HD 172167',
    kind: 'star',
    type: 'A0Va main-sequence star',
    spectral: 'A0Va · 9,600 K',
    distance: '25 light-years',
    ly: 25,
    color: '#cfe0ff',
    size: 8,
    view: 11,
    dir: [-0.18, 0.78, 0.6],
    lore: 'spinning so fast its equator bulges. once the pole star; it will be again.',
  },
  {
    id: 'betelgeuse',
    name: 'Betelgeuse',
    designation: 'α Orionis · HD 39801',
    kind: 'star',
    type: 'M1–2 Ia red supergiant',
    spectral: 'M1–2 Ia · 3,600 K',
    distance: '≈ 640 light-years',
    ly: 640,
    color: '#ff7b6b',
    size: 13,
    view: 20,
    dir: [0.86, -0.3, 0.42],
    lore: 'wide enough to swallow the orbit of jupiter. it dimmed in 2019 and no one knew why.',
  },
  {
    id: 'rigel',
    name: 'Rigel',
    designation: 'β Orionis · HD 34085',
    kind: 'star',
    type: 'B8 Ia blue supergiant',
    spectral: 'B8 Ia · 12,100 K',
    distance: '≈ 860 light-years',
    ly: 860,
    color: '#b9d2ff',
    size: 11,
    view: 16,
    dir: [0.2, -0.62, 0.76],
    lore: 'a hundred and twenty thousand suns of light from a star barely ten million years old.',
  },
  {
    id: 'crab',
    name: 'Crab Pulsar',
    designation: 'PSR B0531+21 · in M1',
    kind: 'pulsar',
    type: 'neutron star, 33 ms period',
    spectral: 'r ≈ 10 km · 1.4 M☉',
    distance: '≈ 6,500 light-years',
    ly: 6500,
    color: '#9fd8ff',
    size: 5,
    view: 16,
    dir: [-0.55, 0.5, -0.67],
    lore: 'the collapsed core of a star seen exploding in 1054. it turns thirty times a second.',
  },
  {
    id: 'albireo',
    name: 'Albireo',
    designation: 'β Cygni · HD 183912',
    kind: 'binary',
    type: 'double star, K3II + B8V',
    spectral: 'K3 II · B8 V',
    distance: '≈ 430 light-years',
    ly: 430,
    color: '#ffd9a8',
    size: 7,
    view: 12,
    dir: [0.05, 0.42, 0.9],
    lore: 'amber and sapphire. whether the two are bound or only passing is still argued.',
  },
  {
    id: 'orion',
    name: 'Orion Nebula',
    designation: 'Messier 42 · NGC 1976',
    kind: 'nebula',
    type: 'H II region, stellar nursery',
    spectral: '≈ 24 light-years across',
    distance: '1,344 light-years',
    ly: 1344,
    color: '#8fb8ff',
    size: 16,
    view: 30,
    dir: [-0.88, 0.12, 0.46],
    lore: 'a nursery you can see with the naked eye. stars are being born in it now.',
  },
  {
    id: 'andromeda',
    name: 'Andromeda',
    designation: 'Messier 31 · NGC 224',
    kind: 'galaxy',
    type: 'barred spiral galaxy',
    spectral: '≈ 1 trillion stars',
    distance: '2.5 million light-years',
    ly: 2.5e6,
    color: '#d8e4ff',
    size: 22,
    view: 34,
    dir: [0.44, 0.62, 0.65],
    lore: 'a trillion stars, falling toward us at 110 km/s. in four billion years, we merge.',
  },
  {
    id: 'polaris',
    name: 'Polaris',
    designation: 'α Ursae Minoris · HD 8890',
    kind: 'star',
    type: 'F7 Ib yellow supergiant, Cepheid',
    spectral: 'F7 Ib · 6,015 K',
    distance: '≈ 433 light-years',
    ly: 433,
    color: '#fff1d6',
    size: 7,
    view: 11,
    dir: [-0.28, -0.7, -0.66],
    lore: 'the pole star. it brightens and dims on a four-day cycle, and the cycle is drifting.',
  },
];

export const stars = raw.map((s) => {
  const dir = new THREE.Vector3(...s.dir).normalize();
  return { ...s, dirVec: dir, position: dir.clone().multiplyScalar(STAR_SHELL) };
});

export const starById = Object.fromEntries(stars.map((s) => [s.id, s]));
export const getStar = (id) => starById[id];
